name       : exa
version    : 0.8.0
release    : 2
source     :
    - https://github.com/ogham/exa/archive/v0.8.0.tar.gz : 07085fd784d553b7c3b62b5a52e4635580d6154f47e6d64245ec0588638dee3e
license    : MIT
component  : system.utils
networking : yes
summary    : A modern replacement for ls
description: |
    exa is a modern replacement for ls. It uses colours for information by default, helping you distinguish between many types of files, such as whether you are the owner, or in the owning group. It also has extra features not present in the original ls, such as viewing the Git status for a directory, or recursing into directories with a tree view. exa is written in Rust, so it’s small, fast, and portable.
builddeps  :
    - cargo
build      : |
    %make
install    : |
    %make_install PREFIX=/usr

    install -Dm00644 contrib/completions.bash installdir/usr/share/bash_completions/completions/exa
    install -Dm00644 contrib/completions.zsh installdir/usr/share/zsh/site-functions/_exa
check     : |
    # Disabled because some tests failed on the server (but they all succeeded locally)
    # cargo test
